### ISSUE TITLE
Settings Page Backend Functionality 

### ISSUE THREAD

**Issue by ShawnAviles** [RyanCamburn/cs554-final-project#16]
# Description

Implement correct User CRUD calls on frontend from settings page (`src/app/settings/page.tsx`) to properly update the user's information in the firestore database when they press "Update Profile". Ensure user sees a success or fail message via the matnine notification popup - you'll see the dummy message shared when the button is pressed

Dependent on #9

**Comment by jackfgibson** [comment]
Getting Id from user session necessary for updating is Dependent on #2

**Comment by jackfgibson** [comment]
Settings page default values in forms needs to be filled initially with user data from session, dependent on #2
