### ISSUE TITLE
Picking a Component Library

### ISSUE THREAD

**Issue by Caposto** [RyanCamburn/cs554-final-project#3]
# Description

Top 3 Options

- https://ui.shadcn.com/
- https://mui.com/material-ui/
- https://headlessui.com/

Which one of these best matches our proposed features and integrates well with TailwindCSS?

# Definition of Done
- [x] Component library is installed and configured

**Comment by ShawnAviles** [comment]
Due to the importance of forms in our application and customizability of components to be aligned with the NPO's branding in the future, I think we should use [https://mantine.dev/](https://mantine.dev/)

**Comment by ShawnAviles** [comment]
### Mantine vs Shadcn/ui

_Note: I didn't include MUI in my comparison as it's too heavily styled for our use case_

Did some more research, final decision is to use mantine but wanted to share findings:
- Mantine does not directly support react server-components ([another source mentioning it](https://www.reddit.com/r/nextjs/comments/16p7avz/can_anyone_suggest_an_alternative_to_mantine/)) - just something to keep in mind for future
- Shadcn/ui doesn't have a native `multi-select` component. A multi-select was a pretty important component needed for the forms when we planned it out so we will just stick with mantine (https://github.com/shadcn-ui/ui/issues/66)
